services:
  - type: web
    name: arya-telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python Funa.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: RENDER_EXTERNAL_URL
        sync: false
      - key: MONGO_URI
        sync: false
      - key: WEBHOOK_SECRET
        generateValue: true
